import { create } from 'zustand';

// WASM module will be loaded dynamically
type SolBeastBot = any; // Will be properly typed once WASM module is built

interface WasmState {
  bot: SolBeastBot | null;
  initialized: boolean;
  loading: boolean;
  error: string | null;
  
  // Actions
  initializeWasm: () => Promise<void>;
  connectWallet: (address: string) => Promise<any>;
  disconnectWallet: () => void;
  updateSettings: (settings: any) => Promise<void>;
  getHoldings: () => Promise<any>;
  getTrades: () => Promise<any>;
  startBot: (intervalMs?: number) => Promise<void>;
  stopBot: () => Promise<void>;
  getLogs: () => Promise<any>;
  getStats: () => Promise<any>;
  clearLogs: () => Promise<void>;
}

export const useWasmStore = create<WasmState>((set, get) => ({
  bot: null,
  initialized: false,
  loading: false,
  error: null,

  initializeWasm: async () => {
    set({ loading: true, error: null });
    
    try {
      // Dynamically import the WASM module
      // This will be generated by wasm-pack
      const wasmModule = await import('../wasm/sol_beast_wasm');
      
      // Initialize the module
      await wasmModule.default();
      
      // Create bot instance
      const bot = new wasmModule.SolBeastBot();
      
      // Initialize with pump.fun program address (configurable via environment)
      const pumpProgram = import.meta.env.VITE_PUMP_PROGRAM || '6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P';
      bot.initialize(pumpProgram);
      
      set({ bot, initialized: true, loading: false });
      
      console.log('WASM module initialized successfully');
    } catch (error) {
      const msg = error instanceof Error ? error.message : `Failed to initialize: ${String(error)}`
      console.error('Failed to initialize WASM module:', msg);
      set({ 
        error: msg,
        loading: false 
      });
    }
  },

  connectWallet: async (address: string) => {
    const { bot } = get();
    if (!bot) {
      throw new Error('WASM module not initialized');
    }
    
    try {
      const userAccount = await bot.connect_wallet(address);
      console.log('Wallet connected:', userAccount);
      return userAccount;
    } catch (error) {
      console.error('Failed to connect wallet:', error);
      throw error;
    }
  },

  disconnectWallet: () => {
    const { bot } = get();
    if (bot) {
      bot.disconnect_wallet();
    }
  },

  updateSettings: async (settings: any) => {
    const { bot } = get();
    if (!bot) {
      throw new Error('WASM module not initialized');
    }
    
    try {
      await bot.update_settings(settings);
      console.log('Settings updated:', settings);
    } catch (error) {
      console.error('Failed to update settings:', error);
      throw error;
    }
  },

  startBot: async (intervalMs: number = 2000) => {
    const { bot } = get();
    if (!bot) throw new Error('WASM module not initialized');
    try {
      await bot.start_monitoring(intervalMs);
      console.log('WASM bot started monitoring');
    } catch (err) {
      console.error('Failed to start WASM bot:', err);
      throw err;
    }
  },

  stopBot: async () => {
    const { bot } = get();
    if (!bot) throw new Error('WASM module not initialized');
    try {
      await bot.stop_monitoring();
      console.log('WASM bot stopped monitoring');
    } catch (err) {
      console.error('Failed to stop WASM bot:', err);
      throw err;
    }
  },

  getLogs: async () => {
    const { bot } = get();
    if (!bot) throw new Error('WASM module not initialized');
    try {
      const logs = await bot.get_logs();
      // Clear any previous error on success
      set({ error: null })
      return logs;
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err)
      console.error('Failed to get logs:', msg);
      set({ error: msg })
      throw err;
    }
  },

  clearLogs: async () => {
    const { bot } = get();
    if (!bot) throw new Error('WASM module not initialized');
    try {
      await bot.clear_logs();
      console.log('WASM logs cleared');
      // Clear error state and return
      set({ error: null })
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err)
      console.error('Failed to clear WASM logs:', msg)
      set({ error: msg })
      throw err
    }
  },

  getStats: async () => {
    const { bot } = get();
    if (!bot) throw new Error('WASM module not initialized');
    try {
      const stats = await bot.get_stats();
      return stats;
    } catch (err) {
      console.error('Failed to get stats:', err);
      throw err;
    }
  },

  getHoldings: async () => {
    const { bot } = get();
    if (!bot) {
      throw new Error('WASM module not initialized');
    }
    
    try {
      const holdings = await bot.get_holdings();
      return holdings;
    } catch (error) {
      console.error('Failed to get holdings:', error);
      throw error;
    }
  },

  getTrades: async () => {
    const { bot } = get();
    if (!bot) {
      throw new Error('WASM module not initialized');
    }
    
    try {
      const trades = await bot.get_trades();
      return trades;
    } catch (error) {
      console.error('Failed to get trades:', error);
      throw error;
    }
  },
}));
