import { create } from 'zustand';

// WASM module will be loaded dynamically
type SolBeastBot = any; // Will be properly typed once WASM module is built

interface WasmState {
  bot: SolBeastBot | null;
  initialized: boolean;
  loading: boolean;
  error: string | null;
  
  // Actions
  initializeWasm: () => Promise<void>;
  connectWallet: (address: string) => Promise<any>;
  disconnectWallet: () => void;
  updateSettings: (settings: any) => Promise<void>;
  getHoldings: () => Promise<any>;
  getTrades: () => Promise<any>;
}

export const useWasmStore = create<WasmState>((set, get) => ({
  bot: null,
  initialized: false,
  loading: false,
  error: null,

  initializeWasm: async () => {
    set({ loading: true, error: null });
    
    try {
      // Dynamically import the WASM module
      // This will be generated by wasm-pack
      const wasmModule = await import('../wasm/sol_beast_wasm');
      
      // Initialize the module
      await wasmModule.default();
      
      // Create bot instance
      const bot = new wasmModule.SolBeastBot();
      
      // Initialize with pump.fun program address
      const pumpProgram = '6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P';
      bot.initialize(pumpProgram);
      
      set({ bot, initialized: true, loading: false });
      
      console.log('WASM module initialized successfully');
    } catch (error) {
      console.error('Failed to initialize WASM module:', error);
      set({ 
        error: error instanceof Error ? error.message : 'Unknown error',
        loading: false 
      });
    }
  },

  connectWallet: async (address: string) => {
    const { bot } = get();
    if (!bot) {
      throw new Error('WASM module not initialized');
    }
    
    try {
      const userAccount = await bot.connect_wallet(address);
      console.log('Wallet connected:', userAccount);
      return userAccount;
    } catch (error) {
      console.error('Failed to connect wallet:', error);
      throw error;
    }
  },

  disconnectWallet: () => {
    const { bot } = get();
    if (bot) {
      bot.disconnect_wallet();
    }
  },

  updateSettings: async (settings: any) => {
    const { bot } = get();
    if (!bot) {
      throw new Error('WASM module not initialized');
    }
    
    try {
      await bot.update_settings(settings);
      console.log('Settings updated:', settings);
    } catch (error) {
      console.error('Failed to update settings:', error);
      throw error;
    }
  },

  getHoldings: async () => {
    const { bot } = get();
    if (!bot) {
      throw new Error('WASM module not initialized');
    }
    
    try {
      const holdings = await bot.get_holdings();
      return holdings;
    } catch (error) {
      console.error('Failed to get holdings:', error);
      throw error;
    }
  },

  getTrades: async () => {
    const { bot } = get();
    if (!bot) {
      throw new Error('WASM module not initialized');
    }
    
    try {
      const trades = await bot.get_trades();
      return trades;
    } catch (error) {
      console.error('Failed to get trades:', error);
      throw error;
    }
  },
}));
